### ISSUE TITLE
Re-architecture

### ISSUE THREAD

**Issue by birkir** [birkir/react-three-gui#17]
Trying to make this work with React Context instead of EventEmitter.

https://codesandbox.io/s/react-three-gui-refactor-architecture-w9oip

```jsx
export default function App() {
  return (
    <ControlsProvider>
      <Canvas>
        <ambientLight />
        <pointLight position={[10, 10, 10]} />
        <Box />
      </Canvas>
      <Controls />
    </ControlsProvider>
  );
}
```

Any ideas how to store the values better than I am currently doing?

**Comment by Pomevak** [comment]
In my humble opinion, after this re-architecute, `react-three-gui` has lost the flexibility it used to have. In previous versions, I was able to write `useControl` anywhere I want, but right now I have to write it inside the `ControlsProvider`, which causes issues to my projects. Besides, the way you pass the context to `react-three-fiber` is kind of awkward. I think it's better to export `ControlsContext` in addition to `ControlsProvider`, so that it become the user's option to use it in react-three-fiber or not, and makes it possible to write `useControl` anywhere as before.
